name: Run Robot Web UI Test on Windows

on:
  push:
    branches: [ main ]

jobs:
  run-robot-web-test:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          # Download ChromeDriver and move it into PATH
          choco install chromedriver -y
          choco install googlechrome -y

      - name: Run Robot Framework Test
        run: robot tests/
