name: Desktop App Robot Test

on:
  push:
    branches: [ main ]

jobs:
  robot-tests:
    runs-on: [self-hosted]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Add Python to PATH and verify installation
        run: |
         $env:Path += ";C:\Users\rohan\AppData\Local\Programs\Python\Python310;C:\Users\rohan\AppData\Local\Programs\Python\Python310\Scripts"
         echo $env:Path  # Print the updated PATH for debugging
         where python
         where pip
         python --version
         pip --version
        shell: powershell
      
      - name: Run Robot Framework tests
        run: |
          robot tests/
