name: Desktop App Robot Test

on:
  push:
    branches: [ main ]

jobs:
  robot-tests:
    runs-on: [self-hosted]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
    
      - name: Set up Python 3.12.1
        uses: actions/setup-python@v3
        with:
          python-version: 3.12.1
      
      - name: Run Robot Framework tests
        run: |
          robot tests/
